[package]
name = "ethereum-tracker-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
thiserror = "1.0"